version: '3'

services:
  web:
    ports:
      - "80"
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL="api"
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

