version: '3'

services:
  web:
    image: web
    build:
      context: .\Web
      dockerfile: Dockerfile
    ports:
      - "81:80"
  api:
    image: api
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "8001:80"
